---CRUD operations (Create, Read, Update, Delete):
-- DDL (Database definition Language)

--a) CREATE:
CREATE TABLE DUMMY_OFFICES(
    OFFICECODE NUMBER(2) NOT NULL,
    CITY VARCHAR(30) NOT NULL,
    PHONENUM VARCHAR(20)NOT NULL,
    ADDR1 VARCHAR(50) NOT NULL,
    ADDR2 VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY(OFFICECODE)
    );
    
--B) INSERT:
INSERT INTO DUMMY_OFFICES(OFFICECODE, CITY, PHONENUM,ADDR1) 
VALUES (11, 'TORONTO', '+1 456 789 1234', '200 Front St.');

SELECT * FROM DUMMY_OFFICES;

-- INSERTNG MULTIPLE ROWS:
--IF I AM NOT MENTIONING THE SCHEMA THEN WE HAVE TO FOLLOW THE SEQENCE OF THE GIVEN ATTRIBUTRS
INSERT ALL
        INTO DUMMY_OFFICES
        VALUES (10, 'Calgary', '+1 123 456 7895', '100 Calgary St.', NULL)
        
        INTO DUMMY_OFFICES
        VALUES (9, 'Vancouver', '+1 234 569 9745', '100 Van St.', NULL)       
Select * from dual;

SELECT * FROM DUMMY_OFFICES;

--UPDATE
/*
CHANGE ADDRESS OF THE TORONTO-BASED OFFICE IN DUMMY_OFFICES, TO 200 SILVER ST.
*/
UPDATE DUMMY_OFFICES
SET ADDR1 = '200 Silver St.'
WHERE OFFICECODE = 11;

--DELETE
DELETE FROM DUMMY_OFFICES
WHERE OFFICECODE = 11;