-- This is a Single Line Comment.

/*
This is
multi Line
Comment
*/


--All Columns
SELECT * FROM EMPLOYEES;


--Q1. Display the firstname and last name of each employee:
SELECT FIRSTNAME, LASTNAME
FROM EMPLOYEES;

--Q2. DISPLAY THE CUSTOMER NUMBER AND THE AMOUNT FROM THE PAYMENT TABLE:
SELECT CUSTOMERNUMBER, AMOUNT
FROM PAYMENTS;

/*
Aliase
Q3. DISPLAY THE FIRSTNAME, LASTNAME AND EXTENSION OF EACH EMPLOYEE.
DISPLAY THEM UNDER THE COLUMN-NAME 'FN' AND 'LN' AND 'EXT'.
*/
SELECT FIRSTNAME AS FN, LASTNAME AS LN, EXTENSION AS EXT
FROM EMPLOYEES;

/*
Q4. DISPLAY THE FN AND THE LN IN TOGETHER, OF EACH EMPLOYEE,
IN THE NEW COLUMN CALLED 'FULLNAME'
*/
SELECT FIRSTNAME || ' ' || LASTNAME AS FULLNAME
FROM EMPLOYEES;

--CASE-SENSITIVE FIELD ALIASE
SELECT FIRSTNAME || ' ' || LASTNAME AS firstname
FROM EMPLOYEES;

/*
Calculate values, and where keyword:
Q5a. For ORDER_NUMBER = 10127, DISPLAY THE SUBTOTAL FOR EACH ITEM:
DISPLAY THE SUBTOTAL SUCH THAT THE MAXIMUM SUBTOTAL APPEARS FIRTS.
*/
SELECT ORDERNUMBER, PRODUCTCODE AS "ITEM_NUM", QUANTITYORDERED, PRICEEACH AS "UNIT_PRICE", (QUANTITYORDERED * PRICEEACH) AS SUBTOTAL
FROM ORDERDETAILS
WHERE ORDERNUMBER = 10127
ORDER BY (QUANTITYORDERED * PRICEEACH) DESC;


--SELECT ORDERNUMBER AS "ON", PRODUCTCODE, QUANTITYORDERED, PRICEEACH,(QUANTITYORDERED * PRICEEACH) AS SUBTOTAL
--FROM ORDERDETAILS
--WHERE "ON" = 10127 --THIS WILL NOT WORK BECAUSE WHERE EXECUTE FIRST AND IT WILL NOT BE ABLE TO FIND WHAT IS "on"
--ORDER BY (QUANTITYORDERED * PRICEEACH) DESC;

/*
SINGLE-ROW FUNCTIONS:

* 'SINGLE-ROW FUNCTION': WORKS ON A SINGLE ROW; RETURN 1 O/P PER ROW (o/p == Output).
* 'AGGREGATE FUNCTION' (GROUPBY): WORK ON A BUNCH OF ROWS; RETURN 1 o/p PER BUNCH OF ROWS.

----->1)STRING FUNCTIONS: (CONCAT(), UPPER(), LOWER(), SUBSTR(), LENGTH())
Q8. DISPLAY THE FN AND LN TOGETHER, OF EACH EMPLOYEE,
IN A NEW COLUMN CALLED 'FullName'
*/

/*null
Display
a) fn and ln, together, in a new col called "FullName"
b)Uppercase of all the lastname, in a new col
c)lowercase of all the firstnamer, in a new col
d)length of the FullName, in a new col
e)Substring of the FullName, starting from the 2nd character, being 3 character long.
*/

SELECT 
    firstname || ' ' || lastname AS FullName,
    UPPER(lastname) AS UppercaseLastName,
    LOWER(firstname) AS LowercaseFirstName,
    LENGTH(firstname || ' ' || lastname) AS FullNameLength,
    SUBSTR(firstname || ' ' || lastname, 2, 3) AS SubstringFullName
FROM  Employees;
